[package]
name = "Lua_chains"
version = "0.1.0"
edition = "2024"

[dependencies]
mlua = { version = "0.9", features = ["lua54", "vendored"] }
event_chains = "0.2.1"
serde = { version = "1.0.228", features = ["derive"] }
